### ISSUE TITLE
在运行LFW评估时出现了以下错误

### ISSUE THREAD

**Issue by Meow-2** [bubbliiiing/arcface-pytorch#16]
每次都是在 5888/6000 这个地方出现的, 请问可能是什么问题呢
```
Test Epoch: [5888/6000 (96%)]: : 24it [00:12,  1.86it/s]
Traceback (most recent call last):
  File "eval_LFW.py", line 66, in <module>
    test(test_loader, model, png_save_path, log_interval, batch_size, cuda)
  File "/home/zk/project/arcface-pytorch/utils/utils_metrics.py", line 150, in test
    tpr, fpr, accuracy, val, val_std, far, best_thresholds = evaluate(
  File "/home/zk/project/arcface-pytorch/utils/utils_metrics.py", line 14, in evaluate
    val, val_std, far = calculate_val(thresholds, distances,
  File "/home/zk/project/arcface-pytorch/utils/utils_metrics.py", line 81, in calculate_val
    f = interpolate.interp1d(far_train, thresholds, kind='slinear')
  File "/home/zk/.conda/envs/dl/lib/python3.8/site-packages/scipy/interpolate/_interpolate.py", line 571, in __init__
    self._spline = make_interp_spline(xx, yy, k=order,
  File "/home/zk/.conda/envs/dl/lib/python3.8/site-packages/scipy/interpolate/_bsplines.py", line 1252, in make_interp_spline
    raise ValueError("Expect x to not have duplicates")
ValueError: Expect x to not have duplicates
```

**Comment by Meow-2** [comment]
我发现这是 scipy 版本的问题, 可以告诉我你的 scipy 具体版本吗?

**Comment by Meow-2** [comment]
我将 scipy 降级为 1.8.1 解决了这个问题
