### ISSUE TITLE
LFW数据集验证时报错

### ISSUE THREAD

**Issue by 11balanceNB26** [bubbliiiing/arcface-pytorch#20]
开始进行LFW数据集的验证。
Traceback (most recent call last):
  File "train.py", line 337, in <module>
    fit_one_epoch(model_train, model, loss_history, optimizer, epoch, epoch_step, epoch_step_val, gen, gen_val, Epoch, Cuda, LFW_loader, lfw_eval_flag, fp16, scaler, save_period, save_dir, local_rank)
  File "/root/autodl-tmp/arcface-pytorch-main/utils/utils_fit.py", line 114, in fit_one_epoch
    _, _, accuracy, _, _, _, _ = evaluate(distances,labels)
  File "/root/autodl-tmp/arcface-pytorch-main/utils/utils_metrics.py", line 13, in evaluate
    val, val_std, far = calculate_val(thresholds, distances,
  File "/root/autodl-tmp/arcface-pytorch-main/utils/utils_metrics.py", line 72, in calculate_val
    f = interpolate.interp1d(far_train, thresholds, kind='slinear')
  File "/root/miniconda3/lib/python3.8/site-packages/scipy/interpolate/_interpolate.py", line 571, in __init__
    self._spline = make_interp_spline(xx, yy, k=order,
  File "/root/miniconda3/lib/python3.8/site-packages/scipy/interpolate/_bsplines.py", line 1252, in make_interp_spline
    raise ValueError("Expect x to not have duplicates")
ValueError: Expect x to not have duplicates

**Comment by angrebobo** [comment]
Degrading scipy to 1.8.1

**Comment by juren1** [comment]
> 开始进行LFW数据集的验证。 Traceback (most recent call last):回溯（最近一次调用）： File "train.py", line 337, in 文件“train.py"；”，第337行 fit_one_epoch(model_train, model, loss_history, optimizer, epoch, epoch_step, epoch_step_val, gen, gen_val, Epoch, Cuda, LFW_loader, lfw_eval_flag, fp16, scaler, save_period, save_dir, local_rank)fit_one_epoch（model_train, model, loss_history, optimizer, epoch, epoch_step, epoch_step_val, gen, gen_val, epoch, Cuda, LFW_loader, lfw_eval_flag, fp16, scaler, save_period, save_dir, local_rank） File "/root/autodl-tmp/arcface-pytorch-main/utils/utils_fit.py", line 114, in fit_one_epoch文件"；/root/ autotl -tmp/ arcfaces -pytorch-main/utils/utils_fit.py"，第114行，在fit_one_epoch _, _, accuracy, _, _, _, _ = evaluate(distances,labels)_, _, accuracy, _, _, _, _ = evaluate（距离，标签） File "/root/autodl-tmp/arcface-pytorch-main/utils/utils_metrics.py", line 13, in evaluate文件"；/root/ autodel -tmp/ arcfaces -pytorch-main/utils/utils_metrics.py"，第13行，在evaluate val, val_std, far = calculate_val(thresholds, distances,Val, val_std, far = calculate_val(阈值，距离， File "/root/autodl-tmp/arcface-pytorch-main/utils/utils_metrics.py", line 72, in calculate_val文件"；/root/ autodel -tmp/ arcfaces -pytorch-main/utils/utils_metrics.py"，第72行，在calculate_val f = interpolate.interp1d(far_train, thresholds, kind='slinear')F = interpolate.interp1d（far_train, thresholds, kind='slinear'） File "/root/miniconda3/lib/python3.8/site-packages/scipy/interpolate/_interpolate.py", line 571, in **init**文件"；/root/miniconda3/lib/python3.8/site-packages/scipy/interpolate/_interpolate.py" self._spline = make_interp_spline(xx, yy, k=order,自我。_spline = make_interp_spline(xx, yy, k=order， File "/root/miniconda3/lib/python3.8/site-packages/scipy/interpolate/_bsplines.py", line 1252, in make_interp_spline文件"；/root/miniconda3/lib/python3.8/site-packages/scipy/interpolate/_bspline .py"，第1252行，在make_interp_spline .py" raise ValueError("Expect x to not have duplicates")引发ValueError（"；期望x没有重复的"；） ValueError: Expect x to not have duplicatesValueError：期望x没有重复项

解决了吗？
